# Generated by Django 5.0.1 on 2024-02-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
        ),
    ]
